openapi: 3.0.0
info:
  title: 'Practice 11: prc_notes_api'
  version: 1.0.0
  description: ''
servers:
  - url: '{{baseURL}}'
paths:
  /api/v1/notes:
    post:
      summary: Create
      tags: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                  format: utc-millisec
    get:
      summary: Get all
      tags: []
      responses: {}
  /api/v1/notes/2:
    get:
      summary: Get by id
      tags: []
      responses: {}
    put:
      summary: Put by id
      tags: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
  /api/v1/notes/1:
    patch:
      summary: Patch by id
      tags: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
  /api/v1/notes/5:
    delete:
      summary: Delete by id
      tags: []
      responses: {}
